
import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author utkarshgerrard
 */
public class Dashboard extends javax.swing.JFrame {

    Quotes q = new Quotes();

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        scaleImage();
        displayQuotes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        workoutsButton = new javax.swing.JButton();
        dashboardLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        goalSetterButton = new javax.swing.JButton();
        healthtipsButton = new javax.swing.JButton();
        nutritionButton = new javax.swing.JButton();
        leaderBoardButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        quoteTextArea = new javax.swing.JTextArea();
        gainzTrackerButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        workoutsButton.setBackground(new java.awt.Color(255, 0, 0));
        workoutsButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        workoutsButton.setText("WORKOUTS");
        workoutsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workoutsButtonActionPerformed(evt);
            }
        });

        dashboardLabel.setOpaque(true);
        dashboardLabel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        dashboardLabel.setText("DASHBOARD");

        profileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLabelMouseClicked(evt);
            }
        });

        goalSetterButton.setBackground(new java.awt.Color(91, 191, 191));
        goalSetterButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        goalSetterButton.setText("GOAL SETTER");
        goalSetterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goalSetterButtonActionPerformed(evt);
            }
        });

        healthtipsButton.setBackground(new java.awt.Color(3, 201, 169));
        healthtipsButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        healthtipsButton.setText("HEALTH TIPS");
        healthtipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthtipsButtonActionPerformed(evt);
            }
        });

        nutritionButton.setBackground(new java.awt.Color(140, 20, 252));
        nutritionButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nutritionButton.setText("NUTRITION");
        nutritionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutritionButtonActionPerformed(evt);
            }
        });

        leaderBoardButton.setBackground(new java.awt.Color(83, 51, 237));
        leaderBoardButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        leaderBoardButton.setText("LEADERBOARD");
        leaderBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBoardButtonActionPerformed(evt);
            }
        });

        quoteTextArea.setEditable(false);
        quoteTextArea.setColumns(20);
        quoteTextArea.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        quoteTextArea.setLineWrap(true);
        quoteTextArea.setRows(5);
        quoteTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("QUOTE OF THE DAY"));
        jScrollPane1.setViewportView(quoteTextArea);
        quoteTextArea.setEditable(false);

        gainzTrackerButton.setBackground(new java.awt.Color(140, 161, 229));
        gainzTrackerButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        gainzTrackerButton.setText("GAINZ TRACKER");
        gainzTrackerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainzTrackerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(healthtipsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(workoutsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nutritionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gainzTrackerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goalSetterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leaderBoardButton, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nutritionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(workoutsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leaderBoardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gainzTrackerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(healthtipsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goalSetterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profileLabelMouseClicked

    private void workoutsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workoutsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workoutsButtonActionPerformed

    private void goalSetterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goalSetterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goalSetterButtonActionPerformed

    private void healthtipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthtipsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_healthtipsButtonActionPerformed

    private void nutritionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutritionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutritionButtonActionPerformed

    private void leaderBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBoardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaderBoardButtonActionPerformed

    private void gainzTrackerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainzTrackerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gainzTrackerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JButton gainzTrackerButton;
    private javax.swing.JButton goalSetterButton;
    private javax.swing.JButton healthtipsButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leaderBoardButton;
    private javax.swing.JButton nutritionButton;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JTextArea quoteTextArea;
    private javax.swing.JButton workoutsButton;
    // End of variables declaration//GEN-END:variables

    private void scaleImage() {
            ImageIcon icon = new ImageIcon("images/profileImage.png");
            Image img = icon.getImage();
            Image imgScale = img.getScaledInstance(profileLabel.getWidth(), profileLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(imgScale);
            profileLabel.setIcon(scaledIcon);
    }
    
    private void displayQuotes(){

        quoteTextArea.setText(q.returnRandomQuotesFromHashMap());
    }
}
