
import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author utkarshgerrard
 */
public class EditUserInfo extends javax.swing.JFrame {

    /**
     * Creates new form EditUserInfo
     */
    public EditUserInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameJLabel = new javax.swing.JLabel();
        lastNameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        firstNameJTextField1 = new javax.swing.JTextField();
        userNameJLabel = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        passwordJLabel = new javax.swing.JLabel();
        passwordJTextField = new javax.swing.JTextField();
        birthdayJLabel = new javax.swing.JLabel();
        genderJLabel = new javax.swing.JLabel();
        heightJLabel = new javax.swing.JLabel();
        heightJTextField = new javax.swing.JTextField();
        weightJLabel = new javax.swing.JLabel();
        weightJTextField = new javax.swing.JTextField();
        woJLabel = new javax.swing.JLabel();
        woJTextField = new javax.swing.JTextField();
        cancelJButton = new javax.swing.JButton();
        updateJButton = new javax.swing.JButton();
        birthdayJTextField = new javax.swing.JTextField();
        genderJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        firstNameJLabel.setText("First Name *");

        lastNameJTextField.setText(OnlyGainz.userinfo[2]);
        lastNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameJTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Last Name *");

        firstNameJTextField1.setText(OnlyGainz.userinfo[1]);
        firstNameJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameJTextField1ActionPerformed(evt);
            }
        });

        userNameJLabel.setText("Username *");

        userNameJTextField.setText(OnlyGainz.userinfo[3]);

        passwordJLabel.setText("Password *");

        passwordJTextField.setText(OnlyGainz.userinfo[4]);

        birthdayJLabel.setText("Birthday *");

        genderJLabel.setText("Gender");

        heightJLabel.setText("Height (cm)");

        heightJTextField.setText(OnlyGainz.userinfo[7]);

        weightJLabel.setText("Weight (lbs)");

        weightJTextField.setText(OnlyGainz.userinfo[8]);
        weightJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightJTextFieldActionPerformed(evt);
            }
        });

        woJLabel.setText("Workout Experience (yrs)");

        woJTextField.setText(OnlyGainz.userinfo[9]);

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        birthdayJTextField.setText(OnlyGainz.userinfo[5]);

        genderJTextField.setText(OnlyGainz.userinfo[6]);
        genderJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(firstNameJLabel)
                    .addComponent(userNameJLabel)
                    .addComponent(passwordJLabel)
                    .addComponent(birthdayJLabel)
                    .addComponent(genderJLabel)
                    .addComponent(heightJLabel)
                    .addComponent(weightJLabel)
                    .addComponent(woJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lastNameJTextField)
                        .addComponent(firstNameJTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                        .addComponent(userNameJTextField)
                        .addComponent(passwordJTextField))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(genderJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(birthdayJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(woJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addComponent(weightJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(heightJTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameJLabel)
                    .addComponent(firstNameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameJLabel)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLabel)
                    .addComponent(passwordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayJLabel)
                    .addComponent(birthdayJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderJLabel)
                    .addComponent(genderJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightJLabel)
                    .addComponent(heightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightJLabel)
                    .addComponent(weightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(woJLabel)
                    .addComponent(woJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateJButton)
                    .addComponent(cancelJButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJTextFieldActionPerformed

    private void firstNameJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameJTextField1ActionPerformed

    private void weightJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightJTextFieldActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
    {
        if(firstNameJTextField1.getText().isEmpty() || lastNameJTextField.getText().isEmpty() || 
                userNameJTextField.getText().isEmpty() || passwordJTextField.getText().isEmpty() ||
                birthdayJTextField.getText().isEmpty() || weightJTextField.getText().isEmpty() ||
                heightJTextField.getText().isEmpty() || woJTextField.getText().isEmpty() ||
                genderJTextField.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Please enter all required fields");
        }
        else
        {
            
            String [] newUserInfo = { firstNameJTextField1.getText().trim() , lastNameJTextField.getText().trim()           ,
                                 userNameJTextField.getText().trim()        ,      passwordJTextField.getText().trim()      ,
                                 (birthdayJTextField.getText().trim())      ,      genderJTextField.getText().trim()        ,
                                 (weightJTextField.getText().trim())        ,      (heightJTextField.getText().trim())      ,
                                 (woJTextField.getText().trim()) };
            
            try {
            // input the file content to the StringBuffer "input"
            BufferedReader file = new BufferedReader(new FileReader("textfiles/User.txt"));
            StringBuffer inputBuffer = new StringBuffer();
            String line;
            String inputStr = null;

            while ((line = file.readLine()) != null) {
                inputBuffer.append(line);
                inputStr = inputBuffer.toString();

                if(line.contains(OnlyGainz.userinfo[0])){
                    

                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[1] , newUserInfo[0]);
                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[2] , newUserInfo[1]);
                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[3] , newUserInfo[2]);
                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[4] , newUserInfo[3]);
                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[5] , newUserInfo[4]);
                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[6] , newUserInfo[5]);
                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[7] , newUserInfo[6]);
                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[8] , newUserInfo[7]);
                    inputStr = inputStr.replaceFirst(OnlyGainz.userinfo[9] , newUserInfo[8]);
                }
                inputBuffer.append('\n');
            }
            file.close();

            // write the new string with the replaced line OVER the same file
            FileOutputStream fileOut = new FileOutputStream("textfiles/User.txt");
            fileOut.write(inputStr.getBytes());
            fileOut.close();
            
        OnlyGainz.userinfo[1] = newUserInfo[0];
        OnlyGainz.userinfo[2] = newUserInfo[1];
        OnlyGainz.userinfo[3] = newUserInfo[2];
        OnlyGainz.userinfo[4] = newUserInfo[3];
        OnlyGainz.userinfo[5] = newUserInfo[4];
        OnlyGainz.userinfo[6] = newUserInfo[5];
        OnlyGainz.userinfo[7] = newUserInfo[6];
        OnlyGainz.userinfo[8] = newUserInfo[7];
        OnlyGainz.userinfo[9] = newUserInfo[8];
        
        repaint();

            
        } catch (Exception e) {
            System.out.println("Problem reading file.");
        }            
        }

    }
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void genderJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayJLabel;
    private javax.swing.JTextField birthdayJTextField;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField1;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JTextField genderJTextField;
    private javax.swing.JLabel heightJLabel;
    private javax.swing.JTextField heightJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JButton updateJButton;
    private javax.swing.JLabel userNameJLabel;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JLabel weightJLabel;
    private javax.swing.JTextField weightJTextField;
    private javax.swing.JLabel woJLabel;
    private javax.swing.JTextField woJTextField;
    // End of variables declaration//GEN-END:variables


}
