/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author davidflores
 */
public class ExerciseJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExerciseJFrame
     */
    public ExerciseJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        nutritionSource8 = new javax.swing.JLabel();
        nutritionSource11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        nutritionSource9 = new javax.swing.JLabel();
        nutritionSource12 = new javax.swing.JLabel();
        nutritionSource13 = new javax.swing.JLabel();
        nutritionSource14 = new javax.swing.JLabel();
        nutritionSource15 = new javax.swing.JLabel();
        nutritionSource17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nutritionSource10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(792, 559));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(237, 121, 68));
        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(231, 187, 165));
        jButton3.setText("Start");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 200, 60));

        nutritionSource8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nutritionSource8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutritionSource8.setText("HOLD");
        nutritionSource8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(nutritionSource8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 200, 40));

        nutritionSource11.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nutritionSource11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutritionSource11.setText("REGULAR");
        nutritionSource11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(nutritionSource11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 200, 40));

        jButton4.setBackground(new java.awt.Color(237, 121, 68));
        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(231, 187, 165));
        jButton4.setText("Start");
        jButton4.setToolTipText("");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 190, 60));

        nutritionSource9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nutritionSource9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutritionSource9.setText("HOLD");
        nutritionSource9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(nutritionSource9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 190, 40));

        nutritionSource12.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nutritionSource12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutritionSource12.setText("KNUCKLE");
        nutritionSource12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(nutritionSource12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 190, 40));

        nutritionSource13.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nutritionSource13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutritionSource13.setText("REGULAR");
        nutritionSource13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(nutritionSource13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 190, 40));

        nutritionSource14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nutritionSource14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutritionSource14.setText("JUMP");
        nutritionSource14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(nutritionSource14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, 40));

        nutritionSource15.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nutritionSource15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutritionSource15.setText("PUSH-UP");
        getContentPane().add(nutritionSource15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 180, 40));

        nutritionSource17.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nutritionSource17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutritionSource17.setText("SQUAT");
        getContentPane().add(nutritionSource17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 180, 40));

        jPanel1.setBackground(new java.awt.Color(219, 218, 216));

        nutritionSource10.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        nutritionSource10.setText("CHOOSE AN EXERCISE");

        jButton1.setBackground(new java.awt.Color(237, 121, 68));
        jButton1.setForeground(new java.awt.Color(231, 187, 165));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(nutritionSource10, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nutritionSource10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //launch a new screen with a stop watch start and make it the same for all exercises
        this.dispose();
        new ExerciseDataSquatJFrame().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new ExerciseDataPushupJFrame().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new workoutJFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerciseJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nutritionSource10;
    private javax.swing.JLabel nutritionSource11;
    private javax.swing.JLabel nutritionSource12;
    private javax.swing.JLabel nutritionSource13;
    private javax.swing.JLabel nutritionSource14;
    private javax.swing.JLabel nutritionSource15;
    private javax.swing.JLabel nutritionSource17;
    private javax.swing.JLabel nutritionSource8;
    private javax.swing.JLabel nutritionSource9;
    // End of variables declaration//GEN-END:variables
}
