
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lopez816
 */
public class leaderboardJFrame extends javax.swing.JFrame {
    ArrayList<Integer> desc = new ArrayList<Integer>();
    /**
     * Creates new form leaderboardJFrame
     */
    public leaderboardJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        orderLeaderboard();
    }
    
    public void orderLeaderboard() {
        // this function will sort the leadboard 
        // with the top users on the application
        
        // open the user file like so
        File myFile = new File("textfiles/exercise.txt");
        try (Scanner myReader = new Scanner(myFile)) {
            while (myReader.hasNextLine()) {
                String ii = myReader.nextLine();
                String [] err = ii.split(" ");
                
                desc.add(Integer.parseInt(err[2])); // adds all user reps   
                }
            Collections.sort(desc, Collections.reverseOrder()); // sorts reps - largest first
            }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        fillLeaderboardTable();      
    }
    
    public void fillLeaderboardTable() {
        // take the array and fill the table
        // DefaultTableModel model = (DefaultTableModel)leaderboardTable.getModel();
        // int i = 0;
        
        /*
        File myFile = new File("textfiles/exercise.txt");
        try (Scanner myReader = new Scanner(myFile)) {
            while (myReader.hasNextLine()) {
                String ii = myReader.nextLine();
                String [] g = ii.split("  ");
                
                model.addRow(new Object [] {++i, g[0], desc.get(i++)});
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        while(i < desc.size()) {
            model.addRow(new Object [] {i + 1, OnlyGainz.userinfo[3], desc.get(i)});
            i++;
        }
        */
        
        // this function should just add to the leaderboard
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaderboardTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Leaderboard");
        setBackground(new java.awt.Color(102, 204, 255));
        setUndecorated(true);

        leaderboardTable.setForeground(new java.awt.Color(237, 121, 68));
        leaderboardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "lopez816", "700"},
                {"2", "karki005", "600"},
                {"3", "flore510", "500"}
            },
            new String [] {
                "#", "User", "Total Reps"
            }
        ));
        leaderboardTable.setGridColor(new java.awt.Color(204, 204, 204));
        leaderboardTable.setRowHeight(40);
        jScrollPane1.setViewportView(leaderboardTable);

        jLabel1.setText("Search User:");

        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(leaderboardTable.getModel());
        leaderboardTable.getSelectionModel().clearSelection();        
        String text = searchText.getText();
        if (text.trim().length() == 0) {
            //rowSorter.setRowFilter(null);
            JOptionPane.showMessageDialog(null, "Enter a valid search!");
        } else {
            for(int i = 0; i < leaderboardTable.getRowCount(); i++) {
                if(leaderboardTable.getModel().getValueAt(i, 1).equals(text)) {
                    System.out.println(i);
                    leaderboardTable.addRowSelectionInterval(i, i); // highlight row if found 
                }
            }
            // rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_searchTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leaderboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leaderboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leaderboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leaderboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leaderboardJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable leaderboardTable;
    private javax.swing.JTextField searchText;
    // End of variables declaration//GEN-END:variables
}
